Added debug, info and error functions in the backend

diff --git a/cups/boomaga b/cups/boomaga
--- a/cups/boomaga
+++ b/cups/boomaga
@@ -18,6 +18,35 @@ SYSTEM_NAME='@CMAKE_SYSTEM_NAME@'
 
 PREF_ENV_PROGS="kdeinit4 firefox chromium-browser razor-session gnome-session lxsession Xfce4-session"
 
+
+#*******************************************
+#
+#*******************************************
+function debug
+{
+    echo "DEBUG: [Boomaga] $1" >&2
+}
+
+
+#*******************************************
+#
+#*******************************************
+function info
+{
+    echo "INFO: [Boomaga] $1" >&2
+}
+
+
+#*******************************************
+#
+#*******************************************
+function error
+{
+    echo "ERROR: [Boomaga] $1" >&2
+    exit $CUPS_BACKEND_FAILED
+}
+
+
 #*******************************************
 #
 #*******************************************
@@ -127,11 +156,10 @@ function getDbusAddr_SessionFile
     # if present: ":", "localhost:" ."localhost.localdomain:". That is, a display
     # of "localhost:10.0" produces just the number "10"
     dbusDisplay=$(echo ${xDisplay} | cut -d ':' -f 2 | cut -d '.' -f 1)
-    echo "DEBUG: [Boomaga] dbusDisplay: ${dbusDisplay}" >&2
+    debug "dbusDisplay: ${dbusDisplay}"
     if [ "${dbusDisplay}" == "" ];
     then
-      echo "ERROR: Can't extract D-Bus display num from '${xDisplay}' for user '$user' (UID: $uid)" >&2
-      exit $CUPS_BACKEND_FAILED
+      error "Can't extract D-Bus display num from '${xDisplay}' for user '$user' (UID: $uid)"
     fi
   else
     dbusDisplay='*'
@@ -139,30 +167,26 @@ function getDbusAddr_SessionFile
 
   if [ ! -f "${DBUS_MACINE_ID_DIR}/machine-id" ];
   then
-    echo "ERROR: Dbus machine-id file '${DBUS_MACINE_ID_DIR}/machine-id' not found." >&2
-    exit $CUPS_BACKEND_FAILED
+    error "Dbus machine-id file '${DBUS_MACINE_ID_DIR}/machine-id' not found."
   fi
 
   userDbusDir="${homeDir}/.dbus/session-bus/"
   if [ ! -d "${userDbusDir}" ]; then
-    echo "ERROR: User Dbus session directory '${userDbusDir}' not found." >&2
-    exit $CUPS_BACKEND_FAILED
+    error "User Dbus session directory '${userDbusDir}' not found."
   fi
-  echo "DEBUG: [Boomaga] User Dbus session directory '${userDbusDir}." >&2
+  debug "User Dbus session directory '${userDbusDir}'."
 
   dbusSessionFile=$(ls ${userDbusDir}$(cat "${DBUS_MACINE_ID_DIR}/machine-id" 2>/dev/null)-${dbusDisplay} 2>/dev/null | head -n 1 )
   if [ -z "${dbusSessionFile}" ] || [ ! -f ${dbusSessionFile} ];
   then
-   echo "ERROR: Dbus session file '${dbusSessionFile}' not found." >&2
-   exit $CUPS_BACKEND_FAILED
+   error "Dbus session file '${dbusSessionFile}' not found."
  fi
-  echo "DEBUG: [Boomaga] dbusSessionFile: ${dbusSessionFile}" >&2
+  debug "dbusSessionFile: ${dbusSessionFile}"
 
   dbusSessionAddress=$(grep DBUS_SESSION_BUS_ADDRESS= ${dbusSessionFile} | cut -d "=" -f 2-)
   if [ "${dbusSessionAddress}" == "" ];
   then
-    echo "ERROR: Can't extract D-Bus bus address from '${dbusSessionFile}' for user '$user' (UID: $uid)" >&2
-    exit $CUPS_BACKEND_FAILED
+    error "Can't extract D-Bus bus address from '${dbusSessionFile}' for user '$user' (UID: $uid)"
   fi
 }
 
@@ -235,18 +259,16 @@ homeDir=$(getent passwd ${user} | cut -d':' -f 6)
 
 if [ "${uid}" == "" ];
 then
-  echo "ERROR: Can't found UID for user '${user}'" >&2
-  exit $CUPS_BACKEND_FAILED
+  error "Can't found UID for user '${user}'"
 fi
 
 if [ "${homeDir}" == "" ];
 then
-  echo "ERROR: Can't found home directory for user '$user' (UID: $uid)" >&2
-  exit $CUPS_BACKEND_FAILED
+  error "Can't found home directory for user '$user' (UID: $uid)"
 fi
 
-echo "DEBUG: [Boomaga] User: $user" >&2
-echo "DEBUG: [Boomaga] Uid:  $uid" >&2
+debug "User: $user"
+debug "Uid:  $uid"
 
 jobFileDir=${homeDir}/.cache
 jobFile=${jobFileDir}/boomaga_in_file-${jobID}.pdf
@@ -261,9 +283,9 @@ getActiveSessionDisplay_consolekit
 
 if [ "${xDisplay}" = "" ];
 then
-  echo "INFO: Can't found active session for user '$user' (UID: $uid)." >&2
+  info "Can't found active session for user '$user' (UID: $uid)."
 fi
-echo "DEBUG: [Boomaga] xDisplay: ${xDisplay}" >&2
+debug "xDisplay: ${xDisplay}"
 
 if [ "$SYSTEM_NAME" == 'Linux' ]; then
   getDbusAddr_Linux_Proc
@@ -275,12 +297,11 @@ fi
 
 if [ "${dbusSessionAddress}" == "" ];
 then
-  echo "ERROR: Can't extract D-Bus bus address from /proc files for user '$user' (UID: $uid)" >&2
-  exit $CUPS_BACKEND_FAILED
+  error "Can't extract D-Bus bus address from /proc files for user '$user' (UID: $uid)"
 fi
 
 
-echo "DEBUG: [Boomaga] dbusSessionAddress: ${dbusSessionAddress}" >&2
+debug "dbusSessionAddress: ${dbusSessionAddress}"
 
 cmd="dbus-send --session --type=method_call --print-reply \
   --dest=org.boomaga /boomaga \
@@ -289,7 +310,7 @@ cmd="dbus-send --session --type=method_call --print-reply \
   string:'${title}' \
   boolean:true"
 
-echo "DEBUG: [Boomaga] command: ${cmd}" >&2
+debug "command: ${cmd}"
 
 errorLog="/tmp/boomaga_${jobID}.err"
 res=${CUPS_BACKEND_OK}
